version: '3'
services:
    blog:
        build:
            context: ./runtimes
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: zhouxufeng/blog
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - blog
        depends_on:
            - mysql
            - redis
            - mailpit
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - '../docker/mysql/data:/var/lib/mysql'
            - '../docker/mysql/shared:/var/lib/mysql_shared'
        networks:
            - blog
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - '../docker/redis/data:/data'
        networks:
            - blog
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - blog
    nginx:
        image: nginx:1.21-alpine
        volumes:
            - ../docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ../docker/nginx/certs:/etc/nginx/certs
        ports:
            - '${NGINX_PORT:-80}:80'
            - '${NGINX_SSL_PORT:-443}:443'
        networks:
            - blog
networks:
    blog:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
